name: Docker Build and Tag

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Build and tag Docker image
        run: docker build -t my-app:v1.0 -t my-app:${{ github.run_number }} .
